victim_dataset: 'gbusg'
victim_arch: 'radformer'
victim_model_path: '/home/ankita/mnt/data_msa_medical/victim_models/radformer/radformer.pkl'
victim_data_root: '/home/ankita/mnt/data_msa_medical/GBCU-Shared'
num_classes: 3
img_size: 224

dataset: 'GBUSV'
subset: 128116
net: 'resnet50'
net_from_name: False
thief_root: '/home/ankita/mnt/data_msa_medical/GBUSV-Shared'
use_pretrain: True
pretrained_dir: '/home/ankita/mnt/data_msa_medical/ckpts/resnet50-imagenet1k.pth'
warmstart: False
load_labeled_set: True

labeled_set_path: '/home/ankita/mnt/data_msa_medical/results_ankita/gbusg_radformer/GBUSV_resnet50/SGD/5000_val500/random_v4/X_trial_1_cycle_1_labeled_set.npy'
val_set_path: '/home/ankita/mnt/data_msa_medical/results_ankita/gbusg_radformer/GBUSV_resnet50/SGD/5000_val500/random_v4/X_trial_1_cycle_1_val_set.npy'
save_dir: 'saved_models/radformer'

save_name: 'fixmatch_v13'

scheduler_type: 'cosine_fixmatch'
# scheduler_type: 'cosine'  #'cosine_fixmatch'
epoch: 100
warmup_epoch: 10

la: False
tro: 1
lr: 0.02  #0.0005

ulb_loss_ratio: 1  #1  #10

algorithm: fixmatch
no_progress: True
expand_labels: True
eval_step: 234
local_rank: -1
num_labels: 5000
warmup: 0

resume: False
# load_path: ./saved_models/caltech_5k_kcenter_fixmatch_la/latest_model.pth
overwrite: True
use_tensorboard: True
# epoch: 100
num_train_iter: 900000
num_eval_iter: 234
num_log_iter: 234
batch_size: 16
eval_batch_size: 16
num_warmup_iter: 5120
uratio: 7
ema_m: 0.999
hard_label: True
T: 1
p_cutoff: 0.95
crop_ratio: 0.875
optim: SGD
momentum: 0.9
weight_decay: 0.00005
layer_decay: 0.5
amp: False
clip: 0.0

train_sampler: RandomSampler
num_workers: 4
seed: 5
ds_seed: 123
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10006
dist_backend: nccl
gpu: None