VICTIM:
  ARCH: 'resnet18'
  DATASET: 'pocus'
  DATA_ROOT: '/home/ankita/scratch/data_msa_medical/covid_5_fold'
  PATH: '/home/ankita/scratch/data_msa_medical/victim_models/pocus_resnet18.pth.tar'
  WIDTH: 224
  HEIGHT: 224
THIEF:
  ARCH: 'resnet50'
  DATA_ROOT: '/home/ankita/scratch/data_msa_medical/Butte'
  DATASET: 'butterfly'
  SUBSET: 128116
  HARD_LABELS: True
ACTIVE:
  BUDGET: 1000
  METHOD: 'entropy'
  CYCLES: 5
  USE_PRETRAINED: True
  PRETRAINED_PATH : '/home/ankita/scratch/data_msa_medical/ckpts/resnet50-imagenet1k.pth'
  ALPHA: 0.2  # only used when hard_labels is False
  TEMP: 1.0   # only used when hard_labels is False
  LA: False
RNG_SEED: 1
TRIALS: 5
METHOD_NAME: 'v4'
OUT_DIR: '/home/ankita/scratch/data_msa_medical/results_ankita/'
TRAIN:
  BATCH: 16 #128 #16
  MOMENTUM: 0.9
  EPOCH: 100
  OPTIMIZER: "SGD"
  LR: 0.02
  MILESTONES: [20,40,60,80]
  WDECAY: 0.0005
  # BATCH: 128
  # MOMENTUM: 0.9
  # EPOCH: 50
  # OPTIMIZER: "SGD"
  # LR: 0.02 # 0.02
  # MILESTONES: [60,120,180]
  # WDECAY: 0.0005