VICTIM:
  ARCH: 'radformer'
  DATASET: 'gbusg'
  DATA_ROOT: '/home/ankita/scratch/data_msa_medical/GBCU-Shared'
  PATH: '/home/ankita/scratch/data_msa_medical/victim_models/radformer/radformer.pkl'
  WIDTH: 299
  HEIGHT: 299
THIEF:
  ARCH: 'inception_v3'
  DATA_ROOT: '/home/ankita/scratch/data_msa_medical/GBUSV-Shared'
  DATASET: 'GBUSV'
  SUBSET: 128116
  HARD_LABELS: True
ACTIVE:
  BUDGET: 5000
  METHOD: 'random'
  CYCLES: 1
  USE_PRETRAINED: True
  PRETRAINED_PATH : '/home/ankita/scratch/data_msa_medical/ckpts/inception_v3_google-0cc3c7bd.pth'
  ALPHA: 0.2  # only used when hard_labels is False
  TEMP: 1.0   # only used when hard_labels is False
RNG_SEED: 1
TRIALS: 3
METHOD_NAME: ''
OUT_DIR: '/home/ankita/scratch/data_msa_medical/results_ankita'
TRAIN:
  BATCH: 16
  MOMENTUM: 0.9
  EPOCH: 100
  OPTIMIZER: "SGD"
  LR: 0.005 
  MILESTONES: [20,40,60,80]
  WDECAY: 0.0005
  # BATCH: 128
  # MOMENTUM: 0.9
  # EPOCH: 50
  # OPTIMIZER: "SGD"
  # LR: 0.02 # 0.02
  # MILESTONES: [60,120,180]
  # WDECAY: 0.0005