VICTIM:
  ARCH: 'radformer'
  DATASET: 'gbusg'
<<<<<<< HEAD
  DATA_ROOT: '/home/ankita/scratch/data_msa_medical/GBCU-Shared'
  PATH: '/home/ankita/scratch/data_msa_medical/victim_models/radformer/radformer.pkl'
=======
  DATA_ROOT: '/home/deepankar/mnt/vision3_data_ckpts_msa_medical/GBCU-Shared'
  PATH: '/home/deepankar/mnt/vision3_data_ckpts_msa_medical/victim_models/radformer/radformer.pkl'
>>>>>>> ba1060430d61521041e28b47a409dc50ce80da3d
  WIDTH: 224
  HEIGHT: 224
THIEF:
  ARCH: 'deit'
<<<<<<< HEAD
  DATA_ROOT: '/home/ankita/scratch/data_msa_medical/GBUSV-Shared'
=======
  DATA_ROOT: '/home/deepankar/mnt/vision3_data_ckpts_msa_medical/GBUSV-Shared'
>>>>>>> ba1060430d61521041e28b47a409dc50ce80da3d
  DATASET: 'GBUSV'
  SUBSET: 128116
  HARD_LABELS: True
ACTIVE:
<<<<<<< HEAD
  BUDGET: 5000
  METHOD: 'random'
  CYCLES: 1
  USE_PRETRAINED: True
  PRETRAINED_PATH : '/home/ankita/scratch/data_msa_medical/ckpts/deit_base_patch16_224-b5f2ef4d.pth'
  ALPHA: 0.2  # only used when hard_labels is False
  TEMP: 1.0   # only used when hard_labels is False
RNG_SEED: 1
TRIALS: 3
METHOD_NAME: ''
OUT_DIR: '/home/ankita/scratch/data_msa_medical/results_ankita'
=======
  BUDGET: 1000
  METHOD: 'random'
  CYCLES: 1
  USE_PRETRAINED: True
  PRETRAINED_PATH : '/home/deepankar/scratch/MSA_Medical/activethief/pretrained/deit_base_patch16_224-b5f2ef4d.pth'
  ALPHA: 0.2  # only used when hard_labels is False
  TEMP: 1.0   # only used when hard_labels is False
RNG_SEED: 5
METHOD_NAME: 'v1'
OUT_DIR: '/home/deepankar/scratch/MSA_Medical/results_1k'
>>>>>>> ba1060430d61521041e28b47a409dc50ce80da3d
TRAIN:
  BATCH: 16
  MOMENTUM: 0.9
  EPOCH: 100
  OPTIMIZER: "SGD"
  LR: 0.005 
  MILESTONES: [20,40,60,80]
  WDECAY: 0.0005
  # BATCH: 128
  # MOMENTUM: 0.9
  # EPOCH: 50
  # OPTIMIZER: "SGD"
  # LR: 0.02 # 0.02
  # MILESTONES: [60,120,180]
  # WDECAY: 0.0005