VICTIM:
  ARCH: 'radformer'
  DATASET: 'gbusg'
  DATA_ROOT: '/home/deepankar/mnt/vision3_data_ckpts_msa_medical/GBCU-Shared'
  PATH: '/home/deepankar/mnt/vision3_data_ckpts_msa_medical/victim_models/radformer/radformer.pkl'
  WIDTH: 224
  HEIGHT: 224
THIEF:
  ARCH: 'radformer'
  DATA_ROOT: '/home/deepankar/mnt/vision3_data_ckpts_msa_medical/GBUSV-Shared'
  DATASET: 'GBUSV'
  SUBSET: 128116
ACTIVE:
  BUDGET: 1000
  METHOD: 'random'
  CYCLES: 1
  USE_PRETRAINED: False
  PRETRAINED_PATH : '/home/deepankar/mnt/vision3_data_ckpts_msa_medical/ckpts/resnet50-imagenet1k.pth'
RNG_SEED: 5
METHOD_NAME: 'v1_transforms'
OUT_DIR: '/home/deepankar/scratch/MSA_Medical/results_1k'
TRAIN:
  BATCH: 32
  MOMENTUM: 0.9
  EPOCH: 50
  OPTIMIZER: "SGD"
  LR: 0.0003  # 0.005
  MILESTONES: [10,20,30,40]
  WDECAY: 0.0005