VICTIM:
  ARCH: 'radformer'
  DATASET: 'gbusg'
  DATA_ROOT: '/home/deepankar/mnt/vision3_data_ckpts_msa_medical/GBCU-Shared'
  PATH: '/home/deepankar/mnt/vision3_data_ckpts_msa_medical/victim_models/radformer/radformer.pkl'
  WIDTH: 224
  HEIGHT: 224
THIEF:
  ARCH: 'resnet101'
  DATA_ROOT: '/home/deepankar/mnt/vision3_data_ckpts_msa_medical/GBUSV-Shared'
  DATASET: 'GBUSV'
  SUBSET: 128116
  HARD_LABELS: True
ACTIVE:
  BUDGET: 5000
  METHOD: 'random'
  CYCLES: 1
  USE_PRETRAINED: True
  PRETRAINED_PATH : '/home/deepankar/scratch/MSA_Medical/pretrained_resnet_models/resnet101-63fe2227.pth'
  ALPHA: 0.2  # only used when hard_labels is False
  TEMP: 1.0   # only used when hard_labels is False
RNG_SEED: 1
METHOD_NAME: 'v8_resnet101_transforms_without_normalize'
OUT_DIR: '/home/deepankar/scratch/MSA_Medical/results_deepankar'
TRAIN:
  BATCH: 16
  MOMENTUM: 0.9
  EPOCH: 100
  OPTIMIZER: "SGD"
  LR: 0.005 
  MILESTONES: [20,40,60,80]
  WDECAY: 0.0005
  # BATCH: 128
  # MOMENTUM: 0.9
  # EPOCH: 50
  # OPTIMIZER: "SGD"
  # LR: 0.02 # 0.02
  # MILESTONES: [60,120,180]
  # WDECAY: 0.0005